title: INGENIEUR JULLIAN PARK
description: Challenger and Web programmer

url: http://chrisaor.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: chrisoar
   facebook: ch_park_best
   instagram: ch_park_best
   email: pchpch0070@gmail.com


google_analytics: "UA-58263416-1"
