# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            JULIAN PARK
tagline:          'A Jekyll theme'
description:      Challenger, Web Programmer
url:              https://chrisaor.github.io/
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          1.0

github:           https://github.com/Chrisaor/
