# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CHALLENGER JULIAN PARK
tagline:          'A Jekyll theme'
description:      Challenger, Web Programmer
url:              https://chrisaor.github.io/
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/Chrisaor/
